kartolo/direct_mail

Classes/Dmailer.php, Documentation/Configuration/Hooks/Index.rst
Also hand over the recipient row to sendTheMail in order to make personalized mail headers possible (for example to make headers like List-Unsubscribe possible)
resolves  #46240
=> [FEATURE] Add a hook for manipulating the mail headers before sending

pi1/class.tx_directmail_pi1.php
Adopt the changes recommend in #8
=> [FIX] Changes access to the database to TYPO3_DB

Classes/Hooks/TypoScriptFrontendController.php
Resolves: #24
Releases: master
Change-Id: Ie95d092eb93c3db287c179824e7121ffc4e5aa7a
=> [BUGFIX] set FE group per hook

composer.json
* use correct typo3-ter name in replace section
* add missing alias map definition
=> Fix composer.json file

Classes/DirectMailUtility.php
=> [BUGFIX] declare getFEgroupSubgroups as static function

Classes/DirectMailUtility.php
=> [BUGFIX] Support HTTP Username/Password on Websites running on https

ext_emconf.php
=> [BUGFIX] Remove jumpurl max version restriction

Classes/Scheduler/AnalyzeBounceMail.php
=> [BUGFIX] Marked processed mail deleted and expunge the deleted mail

composer.json
Fixes package naming to use current (up-to-date) projects of the required packages.
=> [BUGFIX] fixed required packages names and versions

Classes/Module/Dmail.php
=> fix distribution time

Resources/Private/Php/Fetch/src/Fetch/Message.php
Resolves #68 
@wiggum70 please check this
=> check for rfc822 subtype. This include rfc822-headers

Classes/Hooks/JumpurlController.php
=> BUGFIX: Encode # char in jumpurls

Documentation/KnownProblems/Index.rst
Hey Ivan, need to bother you one more time today, saw that I overlooked the forge link in the reST files.
=> [FEATURE] Followup: Remove Forge from docs

Classes/Module/Statistics.php
=> [BUGFIX] Exception in statistics module when trying to remove recipients

Classes/Scheduler/AnalyzeBounceMail.php, Resources/Private/Php/Fetch/src/Fetch/Message.php
I tested the patch by @linkpool (ZIP file in issue #102) and was able to fetch mails with it. Therefore I pasted this into a commit and create this PR so that you may take a look at the code changes.
=> [WIP] Fix bounce mail handling

Classes/Dmailer.php
=> [BUGFIX] fix SQL query

Classes/Hooks/JumpurlController.php
=> [BUGFIX] corrected jumpurl hook

Classes/DirectMailUtility.php, Documentation/Configuration/InstallingTheExtension/Index.rst, ext_conf_template.txt, ext_localconf.php
=> #164 UseImplicitPortToFetch option

Classes/Module/RecipientList.php
Fixes issue stated in #180 so editors can view recipients in plain list view
=> [Bugfix] Fix check on table permissions for plain lists (resolves #180)

Classes/Module/Statistics.php
=> [BUGFIX] third argument of update() must be an array

Classes/Dmailer.php
=> [BUGFIX] enable jumpurl for https in plaintext mode

Classes/DirectMailUtility.php
Changed link generation so that it also works with the Sitemanagment and PageTypeSuffix
=> Get URL with pagetype even when using sitemanagment

Classes/DirectMailUtility.php
=> [BUGFIX] detect how the parameter need to be glued

Classes/Importer.php
=> fix: Reads the correct import configuration

Classes/Hooks/JumpurlController.php
=> [BUGFIX] restore dmailerping

Classes/Module/Dmail.php
=> [BUGFIX] get domain based on PID for quickmail

Classes/Middleware/JumpurlController.php
The FrontendUser's table name is fe_users.
=> [BUGFIX] Fix table name in JumpurlController

Classes/Module/BaseScriptClass.php, Classes/SelectCategories.php
=> [BUGFIX] fix SQL to fit static_info_tables 6.9.0

Documentation/Configuration/ConfiguringTheUseOfCategories/Index.rst
=> [TASK] Remove TS code in docu and replace it with link to the TS file

Classes/Dmailer.php, Classes/Importer.php, Classes/Module/Statistics.php
Use fopen if option allow_url_fopen is enabled because fopen is faster than getUrl.
=> [TASK] Improve inclusion of media + [BUGFIX] Fix setting of textarea width

Classes/Importer.php
make some adjustment to the importer class to make it compatible on TYPO3 10 LTS
Releases: develop
=> [TASK] CSV Importer for TYPO3 10 LTS

Classes/Dmailer.php
=> [BUGFIX] add table name on the selected field

Classes/Dmailer.php
Resolves: #240
Releases: develop
=> [BUGFIX] add missing dot for field name

Classes/Scheduler/AnalyzeBounceMailAdditionalFields.php, Classes/Scheduler/MailFromDraftAdditionalFields.php
Resolves: #253
Releases: develop
=> [BUGFIX] fix deprecated addMessage in the scheduler additionalField

Classes/Dmailer.php
Resolves: #247
Releases: develop
=> [BUGFIX] don't send empty HTML part

composer.json
https://github.com/FriendsOfTYPO3/tt_address/blob/master/Documentation/Administration/Changelog/v/6-0-0.rst
=> [TASK] Allow tt_address ^6.0

Classes/MailSelect.php
Resolves: #294
Releases: v8.0.0-alpha
=> [TASK] remove control character

Configuration/TypoScript/plaintext/setup.typoscript
See https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Setup/Config/Index.html#additionalheaders
=> Make content-type header appear in plaintext page type

ext_localconf.php
=> fix: use correct path to file

Classes/Dmailer.php
=> [BUGFIX] fix undefined array key

Classes/Module/RecipientListController.php
=> [BUGFIX] fix PHP warning

Classes/Dmailer.php
=> [BUGFIX] Prevent type error when no categories are defined

composer.json
=> Task #460: fix composer.json to be able to release to packagist

Classes/Dmailer.php
=> Fix unsafe array access to $mediaData['use_jumpurl']

Classes/Plugin/DirectMail.php
=> [BUGFIX] Cast line length to int
