kartolo/direct_mail

- ext_localconf.php
usable fields in markers.
I know that Its possible to add this over $extConf['addRecipFields'] but
tt_address default values (since a long time) is tt_address.first_name and first_name.last_name and not the compound tt_address.name anymore
so please update this..
thanks
>  add first_name and last_name field of tt_address to the default

- Classes/Module/Statistics.php
The icon to "Disable returned recipients" cannot be found. This commit replace that icon with a lock icon.
> [BUGFIX] Fix missing icon in Statistics module

- Classes/Hooks/JumpurlController.php
In the new Hook/JumpurlController $GLOBALS['TSFE']->initFEuser(); is called before $GLOBALS['TSFE'] is initiated.
Removed the call as this is done after the hook in RequestHandler/handleRequest
> [BUGFIX] Removed $GLOBALS['TSFE']->initFEuser(); from Jumpurl Hook

- Classes/Dmailer.php
- Tests/Unit/Dmailer/DirectMailEngineTest.php
For some special cases as shown by the unit tests the method
"extractHyperLinks" fails to properly extract the appropriate
values. The unit tests fail.
This patch solves the issue and makes the unit tests working
again.
Resolves: https://github.com/kartolo/direct_mail/issues/12
Releases: master
> [BUGFIX] Fix issue with "extractHyperLinks"

- Classes/DirectMailUtility.php
- Classes/Scheduler/MailFromDraft.php
If fetching of new content failed throw an exception with the error
from DirectMailUtility::fetchUrlContentsForDirectMailRecord().
This prevents old mail being send to the receivers. And makes the
error visible for the admin in the BE.
> [BUGFIX] Don't schedule draft mail if fetching new content failed

- ext_emconf.php
As the extension uses the "::class" keyword/operator the PHP version requirement has to get raised to 5.5
> Updated PHP version requirement

- Classes/Module/Statistics.php
- Documentation/Configuration/Hooks/Index.rst
This adds a simple hook to allow a more fine-grained control of the statistics link response output.
> [FEATURE] Add a new hook for link reponse output

- Classes/DirectMailUtility.php
wenn SQL is set to strict, SQL shows error since attachment is blob and it needs default value
Resolves #52
> [BUGFIX] set empty value for attachment

- Classes/DirectMailUtility.php
Sometimes the server security policy doesn't allow to fetch pages when user-agent is not given. With this patch we can add the user-agent when fetching the content  of a page.
Related to #67
> Add user-agent when fetching content of a page

- Classes/Module/Dmail.php
This renders a larger select field for multiple mail groups. We use a TYPO3 typical CSS class and the size attribute to modify the select field.
> [TASK] Use larger select field for multiple mail groups

- composer.json
Allow installation via composer in typo3 v8.7 again.
> [BUGFIX] fix typo3/cms-core version range in composer.json

- Classes/Module/Dmail.php
When saving the distribution time it now parses to correct timestamp. Tested in TYPO3 8.
> [FIX] Use correct function to parse string to timestamp

- Classes/DirectMailUtility.php
As there is no /tmp directory on windows systems debug output results in an error.
Core: Error handler (BE): PHP Warning: file_put_contents(/tmp/dmail.php): failed to open stream: No such file or directory in C:\wwwroot\...\typo3conf\ext\direct_mail\Classes\DirectMailUtility.php line 1227
> No /tmp directory on windows systems

- Classes/Scheduler/AnalyzeBounceMailAdditionalFields.php
The additional field »service« in the task for the bounce
mail handling was not retrieved correctly before and
caused the form to preset “IMAP” every time.
Grab the correct object method to use the existing value.
> Fix additional fields in bounce task

- README.md
Since Forge is [not used anymore](https://forge.typo3.org/issues/82947#note-2) I quickly updated this in the README:
* Remove link to forge
* Add links to TER & Packagist
* Explain "develop" branch in contribution guideline
> README: Remove Forge

- Classes/DirectMailUtility.php
On using htaccess and https url's the user and password will not be set in the url.
Therefore fetching content fails.
> [BUGFIX] Fix setting user and password in fetch url

- Classes/Dmailer.php
The method Dmailer::removeHTMLComments already allows for downlevel hidden conditional comments, but removes downlevel revealed comments.
This fix changes that.
"Normal" comment are still stripped.
> Allow downlevel revealed conditional comments

- Documentation/Configuration/ConfiguringTheDirectMailModuleInPageTsconfig/Index.rst
The `jumpurl_tracking_privacy` property has been listed twice. Also, the first occurence had description for `enable_jump_url` property.
> Fix jumpurl configuration documentation

- Classes/DirectMailUtility.php
- Configuration/TCA/sys_dmail.php
- Configuration/TCA/sys_dmail_category.php
- Configuration/TCA/sys_dmail_group.php
- ext_tables.php
- Fix installation in TYPO3 v9 LTS
- Fix compiling of Recipient List with "Include page subtree" enabled.
> [BUGFIX] for Typo3 v9 compatibility #138

- Classes/Dmailer.php
This hooks allows the list of recipients to be post-processed before
the direct_mail mailer starts sending the messages.
Resolves: #131
> [FEATURE] Add hook to post-process the actual list of recipients

- ext_emconf.php
Fix deprecated-Warning: Extension "direct_mail" defines a dependency on ext:cms, which has been removed. Please remove the dependency.
> Remove deprecated cms dependency

- Configuration/TypoScript/plaintext/setup.txt
To avoid warnings in TYPO3 9.5 LTS log, this commit updates existing Typoscript conditions to Symfony expression language and removes obsolete conditions.
> [TASK] Update Typoscript conditions to Symfony expression language

- ext_localconf.php
Get extension configuration in ext_localconf.php via \TYPO3\CMS\Core\Configuration\ExtensionConfiguration as $_EXTCONF is not avaliable anymore in TYPO3 10.
> [TASK] Update getting of extension configuration

- Classes/Module/NavFrame.php
- Configuration/TCA/sys_dmail.php
- Configuration/TCA/sys_dmail_category.php
- Configuration/TCA/sys_dmail_group.php
- ext_tables.php
Since pages_language_overlay entries has been moved to table pages as new translated entries for its parent language,
those pages will no longer be shown in navigation frame for Newsletter pages.
TYPO3 version 9.5 and 10.4
> [TASK] Exclude translated pages from BE page navigation

- Classes/Dmailer.php
Remove usage of method mime_content_type which does not work with basename($media['absRef'] as argument. Instead use API method embed to embed images with Content-ID standard.
> [BUGFIX] Fix embedding of images

- Classes/Middleware/JumpurlController.php
There are three issues introduced by the rewrite of JumpurlController which are fixed by this pull request:
**1. Authcode validation was broken**
If `authCode_fieldList` is not set explicitly in the direct mail record, the default value provided from the database is `$this->directMailRecord['authcode_fieldList'] = ''`. However, `'' ?? 'uid'` evaluates to `''` which leads to the generation of a non-matching authcode. Using ternary operator resolves this aspect (cp. https://www.php.net/manual/en/types.comparisons.php)
At the same time, the system throws an exception if `$submittedAuthCode === $authCodeToMatch` as the operator was not changed to `!==`. Furthermore, the error message of the exception should not contain the correct authchode for security reasons (closely related to #231 in …
> [BUGFIX] Fix authcode validation, system marker substitution and target url if there is no recepient

- Classes/Hooks/JumpurlController.php
Fixes the exception message thrown in JumpurlController of v6.0.2 if an incorrect authcode is supplied. The original version outputs the correct authcode for an arbitrary user on the system in case debugging output is not configured in a secure way.
I suggest this is an issue that should be fixed for direct_mail v6.0.X and Typo3 v9.
The only thing this PR does is fix the exception message.
Resolves: #231
@kartolo, I am grateful for feedback =)
> [BUGFIX] Fix exception message in case of incorrect authcode

- Classes/DirectMailUtility.php
Removed condition checking for Typo3 9 and removed old default behaviour to fetch title from
pages_language_overlay table - doesn't exist anymore. As the extension is not meant to be backward compatible to Typo3 9 and lower it is safe to remove the compatibility code.
> [BUGFIX]  Selecting translated page in Backend fails with errors

- Classes/Importer.php
if the target file storage used by the csv recipient import does not have a trailing slash in its configured basePath (TYPO3 does not enforce this), the importer will use an invalid path for the file. This results in an infinite loop when trying to read the file.
This PR fixes the invalid path and also adds a check if fopen was successful. The error handling of this could maybe be improved, but at least it prevents the allowed memory size exhausted exception I ran into.
> prevent invalid upload path and infinite loop in csv import

- Classes/Module/MailerEngine.php
currently delete icon is shown on already sent direct_mail
Resolves: #244
> [BUGFIX] delete icon should be shown on queued direct_mail

- Classes/Dmailer.php
Set `sender` instead of `returnPath` to take the defined email address from the `return_path` option into account again for returning/bouncing emails.
resolves #251
> [BUGFIX] set sender instead of returnPath

- Classes/DirectMailUtility.php
In CLI / Scheduler context, $_SERVER['HTTP_HOST'] can be null.
This leads to a malformed URI.
If you need to test this patch on a development machine with a different base URL, make sure to run the scheduler with the proper context, e.g. like this:
`TYPO3_CONTEXT=Development/PK ./typo3cms scheduler:run`
Resolves: #273
> [BUGFIX] Fix empty $_SERVER['HTTP_HOST'] in CLI context

- ext_tables.sql
Change type from tinyblob to blob for url column in sys_dmail_maillog table to avoid exception if data is too long.
This happens if the url is very long (in my case from an online car configurator) and jumpurl is enabled.
resolves #297
> [BUGFIX] Avoid exception if data is too long for url column in sys_dmail_maillog

- Classes/DirectMailUtility.php
- Classes/Dmailer.php
* Core: Error handler (BE): PHP Warning: Undefined array key "metaCharset"
* Core: Error handler (BE): PHP Warning: Undefined array key "forceCharset"
* Core: Error handler (BE): PHP Warning: Undefined array key "enable_jump_url"
* Core: Error handler (BE): PHP Warning: Undefined array key "enable_mailto_jump_url"
With this Step 1 (fetching page) in Direct Mail module has no more warnings
> Resolve warnings due to undefined array keys

- Classes/Hooks/TypoScriptFrontendController.php
- ext_localconf.php
To fetch protected pages the mailer needs to simulate a FE user group. Since the implementation of FE user authentication has changed to user aspect in v11, we need to adjust the implementation. Furthermore, we need to use another hook that comes later in the TypoScriptFrontendController instance
> [TASK] Fix simulate user group

- Classes/Repository/FeUsersRepository.php
Since PDO is in the root namespace, its usage must be prefixed with a backslash.
> [BUGFIX] Use correct namespace for PDO

- Classes/Middleware/JumpurlController.php
If jumpurl is used and a test mail (step 4) is sent, there is nether a mail id (mid) nor an authcode (aC) in the jumpurls:
https://foobar.com/newsletter/?mid=###SYS_MAIL_ID###&aC=###SYS_AUTHCODE###&jumpurl=7
In this case, jumpurl processing should be bypassed to avoid further errors. Furthermore, it makes no sense to log links clicked in test sendings.
> [BUGFIX] Jumpurl: Don't process if mail ID is not numeric

- Classes/Middleware/JumpurlController.php
If jumpurl_tracking_privacy is active, jumpurls are generated without the rid parameter which contains the table and uid of the recipient. Therefore, the rid parameter must not be mandatory.
> [TASK] Make jumpurl work without submitted recipient

- Classes/Module/DmailController.php
- Classes/Module/RecipientListController.php
In a normal, space-separated recipient list, the addresses are stored in a MEDIUMBLOB field. This field is nullable by default, therefore if no list has been entered, the field will have a NULL value. This breaks displaying or using recipient lists, becase preg_split cannot be applied on a NULL value. This is prevented by adding a check before using preg_split.
> [BUGFIX] Space-separated recipient list: Check for null before using preg_split

- Classes/Dmailer.php
function encureCorrectEncoding() expects a string as first argument
> [BUGFIX] User fields might be null

- Classes/Dmailer.php
getPublicUrl() is not meant to be used for local file paths. also See https://forge.typo3.org/issues/99404
> [BUGFIX] Do not use public url for path to attachment

- Classes/Middleware/JumpurlController.php
- ext_tables.sql
**Problem:**
Since the update to the 11 version, we see that the open rate according to the statistics module is significantly lower than for newsletters sent with DirectMail 6.0.2 (see https://github.com/kartolo/direct_mail/issues/379). My guess is that the rid field in the log is not filled properly. 
**Cause:**
First I checked how the number of opened mails is calculated in the first place. This is done here: 
https://github.com/SSFGizmo/direct_mail/blob/c5c796a23667d4bb152a32426a6ecaf0af6fa058/Classes/Repository/SysDmailMaillogRepository.php#L131
The groupBy rid is important to prevent multiple counts. But this also means that the rid must be unique per recipient. And I think that there is currently a problem. 
For the calculation of the open rate, the count of the tracking pixel is …
> [BUGFIX] Store full rid in maillog (resolves #379)

- Classes/Dmailer.php
Without this attachments have names like `fal-tempfile...pdf`
> Use original filename for attachments

- Configuration/TypoScript/plaintext/setup.typoscript
I know this is probably not being used, but on a legacy upgrade project we needed to make this also work.
By default, you get lots of PHP 8.x warnings. This fixes it.
> [BUGFIX] Plaintext rendering and PHP 8.x exceptions

- .editorconfig
- .github/workflows/ci.yml
- .github/workflows/publish-ter.yml
- .gitignore
- .php-cs-fixer.php
- .phpcs.xml
- Build/bin/console
- composer.json
- phpstan.neon
> Task #424: add github actions to lint the code and release to TER

- Documentation/Configuration/EnablingClickStatistics/Index.rst
Clearify documentation for preventing generation of jumpurls to fit new version of direct mail. Added an example (unsubscribe link).  In the old documentation it looked like you had to set a link parameter.
> Update Index.rst (jumpurls)
